### ISSUE TITLE
qqbot报错

### ISSUE THREAD

**Issue by Q3213522398** [TISUnion/ChatBridge#15]
![image](https://user-images.githubusercontent.com/59270149/126090204-394ee560-fc51-473c-88f9-024d63958c3c.png)

**Comment by Q3213522398** [comment]
![image](https://user-images.githubusercontent.com/59270149/126090335-b1219605-9b36-4eb3-8419-cb133ae02140.png)
安装的几个库

**Comment by Fallen-Breath** [comment]
fixed in 2038c109dc0197fe699ed6db3379a0fe31740bf6
