### ISSUE TITLE
部署Kaiheila bot client的时候出现点问题

### ISSUE THREAD

**Issue by TsubakiAwa** [TISUnion/ChatBridge#17]
Python：Python 3.9.2
Windows：Windows10 20H2
ChatBridge：ChatBridge-v2.0.2

requirements.txt：
mcdreforged>=2.2.0
pycryptodome
colorlog
websocket>=0.2.1
websocket-client>=1.2.1
khl.py==0.0.10
parse

C:\Users\Administrators\Desktop\CB>pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: mcdreforged>=2.2.0 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: pycryptodome in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 2)) (3.10.1)
Requirement already satisfied: colorlog in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 3)) (6.5.0)
Requirement already satisfied: websocket>=0.2.1 in c:\Administrators\Administrators\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 4)) (0.2.1)
Requirement already satisfied: websocket-client>=1.2.1 in c:\Administrators\Administrators\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 5)) (1.2.1)
Requirement already satisfied: khl.py==0.0.10 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 6)) (0.0.10)
Requirement already satisfied: parse in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 7)) (1.19.0)
Requirement already satisfied: aiohttp~=3.7.3 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from khl.py==0.0.10->-r requirements.txt (line 6)) (3.7.4)
Requirement already satisfied: pycryptodomex~=3.9.9 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from khl.py==0.0.10->-r requirements.txt (line 6)) (3.9.9)
Requirement already satisfied: ruamel.yaml~=0.17.16 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from mcdreforged>=2.2.0->-r requirements.txt (line 1)) (0.17.16)
Requirement already satisfied: prompt-toolkit~=3.0.19 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from mcdreforged>=2.2.0->-r requirements.txt (line 1)) (3.0.20)
Requirement already satisfied: requests~=2.26.0 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from mcdreforged>=2.2.0->-r requirements.txt (line 1)) (2.26.0)
Requirement already satisfied: colorama>=0.4.4 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from mcdreforged>=2.2.0->-r requirements.txt (line 1)) (0.4.4)
Requirement already satisfied: psutil>=5.8.0 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from mcdreforged>=2.2.0->-r requirements.txt (line 1)) (5.8.0)
Requirement already satisfied: greenlet in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from websocket>=0.2.1->-r requirements.txt (line 4)) (1.1.2)
Requirement already satisfied: gevent in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from websocket>=0.2.1->-r requirements.txt (line 4)) (21.8.0)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from aiohttp~=3.7.3->khl.py==0.0.10->-r requirements.txt (line 6)) (1.6.3)
Requirement already satisfied: chardet<4.0,>=2.0 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from aiohttp~=3.7.3->khl.py==0.0.10->-r requirements.txt (line 6)) (3.0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from aiohttp~=3.7.3->khl.py==0.0.10->-r requirements.txt (line 6)) (5.1.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from aiohttp~=3.7.3->khl.py==0.0.10->-r requirements.txt (line 6)) (20.3.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from aiohttp~=3.7.3->khl.py==0.0.10->-r requirements.txt (line 6)) (3.0.1)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from aiohttp~=3.7.3->khl.py==0.0.10->-r requirements.txt (line 6)) (3.7.4.3)
Requirement already satisfied: wcwidth in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from prompt-toolkit~=3.0.19->mcdreforged>=2.2.0->-r requirements.txt (line 1)) (0.2.5)
Requirement already satisfied: idna<4,>=2.5 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from requests~=2.26.0->mcdreforged>=2.2.0->-r requirements.txt (line 1)) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from requests~=2.26.0->mcdreforged>=2.2.0->-r requirements.txt (line 1)) (2020.6.20)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from requests~=2.26.0->mcdreforged>=2.2.0->-r requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from requests~=2.26.0->mcdreforged>=2.2.0->-r requirements.txt (line 1)) (2.0.7)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from ruamel.yaml~=0.17.16->mcdreforged>=2.2.0->-r requirements.txt (line 1)) (0.2.2)
Requirement already satisfied: setuptools in c:\program files\python39\lib\site-packages (from gevent->websocket>=0.2.1->-r requirements.txt (line 4)) (49.2.1)
Requirement already satisfied: zope.interface in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from gevent->websocket>=0.2.1->-r requirements.txt (line 4)) (5.4.0)
Requirement already satisfied: cffi>=1.12.2 in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from gevent->websocket>=0.2.1->-r requirements.txt (line 4)) (1.14.5)
Requirement already satisfied: zope.event in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from gevent->websocket>=0.2.1->-r requirements.txt (line 4)) (4.5.0)
Requirement already satisfied: pycparser in c:\users\Administrators\appdata\roaming\python\python39\site-packages (from cffi>=1.12.2->gevent->websocket>=0.2.1->-r requirements.txt (line 4)) (2.20)

C:\Users\Administrators\Desktop\CB>python3 -m ChatBridge.pyz kaiheila_bot

C:\Program Files\Python39\python3.exe: Error while finding module specification for 'ChatBridge.pyz' (ModuleNotFoundError: No module named 'ChatBridge')

还有Kaiheila bot client里的client_id，client_secret，token，这个三个是要去开黑啦官方申请内测才有的吗？

**Comment by Fallen-Breath** [comment]
啊，readme 里的启动指令有点问题，都不需要 `-m`。bot 的那三个数据都得自己去申请内测
