### ISSUE TITLE
cqhttp_bot运行后自动关闭

### ISSUE THREAD

**Issue by Djy12345** [TISUnion/ChatBridge#19]
使用go-cqhttp，版本是最新版，能够正常运行。
已经安装几个要求的库
使用python ChatBridge.pyz cqhttp_bot无报错，但自动关闭。
![SharedScreenshot](https://user-images.githubusercontent.com/36471742/148533173-64f349f5-877b-4187-91ae-db291b3e560d.jpg)

**Comment by Djy12345** [comment]
出现新的报错
![SharedScreenshot](https://user-images.githubusercontent.com/36471742/148534771-a7750551-eccd-4544-a978-3846849cfc9c.jpg)

**Comment by xrh0905** [comment]
看起来是连不上ChatBridge Server
能不能看看47.92.254.133:30000上的ChatBridge Server是否正常?
有没有放行30000/tcp?
